### PR TITLE
Fixing division by zero error in tensorflow and pytorch distance files

### PR DESCRIPTION
**Pull request by amirgholipour**
There were some errors related to division by zero in distance files which I fixed them. Also I put some type: ignore comment in cd/utilis.py and cd/tabular.py.

### CODE REVIEW

**Comment by amirgholipour** [comment]
Please review and accept the changes.

**Comment by arnaudvl** [comment]
Thanks for your interest in the repo and the contribution. There are however a few reasons why we cannot merge it in master. Drift detectors compare distributions of data which assumes here the setting of `n, m > 1` and have little power for just a single sample. If you wish to compare a single instance to a distribution, then we advice to use one of the outlier detectors.

**Comment by amirgholipour** [comment]
> Thanks for your interest in the repo and the contribution. There are however a few reasons why we cannot merge it in master. Drift detectors compare distributions of data which assumes here the setting of `n, m > 1` and have little power for just a single sample. If you wish to compare a single instance to a distribution, then we advice to use one of the outlier detectors.

I tried to address the issue with batch training. after that modification you are able to use Autoencoder based outlier detection with any batch size.

the other issue was division by zero error. which is happening when you would like to use the LearnedKernelDrift with tensorflow and pytorch.
At least, please accept division by zero correction one.

**Comment by amirgholipour** [comment]
Please accept correction with division by zero

**Pull request closed without merging**
