### PR TITLE
Add version to metadata

### LINKED ISSUE #236: Add alibi-detect version to metadata

### PR DESCRIPTION
**Pull request by jklaise**
Fixes #236. Takes the same approach as https://github.com/SeldonIO/alibi/pull/481.

### CODE REVIEW

**Comment by jklaise** [comment]
It appears that due to the current tests of comparing the `meta` attribute directly to a literal dictionary, the literal dict would need to include `"version": __version__` for every test.

It might be better to factor out these `meta` dictionaries and use them when initializing the detectors, though this would still necessitate including `"version": __version__` for each one if we keep the same tests.

**Comment by jklaise** [comment]
Latest commit adds `__version__` entry to the metadata tests. This seemed to be the easiest way to fix the tests without doing any refactoring.

**Review by ascillitoe — APPROVED** [review]

**Comment by ascillitoe** [comment]
@jklaise, @arnaudvl:  I've merged this, but a minor follow-up thought, do you think we should move the save/load instructions from "Getting started" to a separate "Saving and loading" page like in alibi? For consistency with alibi but also because I wonder if we could do with adding a warning about different alibi-detect versions like in alibi, and this would start to clutter the "Getting started" page?

**Comment by jklaise** [comment]
Sounds like a good idea.

**Pull request merged**
