### PR TITLE
Update Alibi_Detect_Logo_rgb image with white stroked letters

### PR DESCRIPTION
**Pull request by LakshmanKishore**
This pull request addresses the visibility issue of the Alibi Detect image in the README when using the default dark theme on GitHub. It adds a white stroke to the letters, improving their clarity against the dark background.

Before the changes - README.md:
image

After the changes - README.md:
image

### CODE REVIEW

**Comment by LakshmanKishore** [comment]
Dear maintainers,

I kindly request that you consider tagging this contribution with the 'hacktoberfest-accepted' label or adding the 'hacktoberfest' topic to the repository. This would make it easier for participants in Hacktoberfest to find and contribute to this project.

Thank you!

**Comment by jklaise** [comment]
Thank you for your contribution!

**Comment by LakshmanKishore** [comment]
Hi @jklaise ,

I hope you're doing well. I wanted to express my gratitude for merging this pull request. I noticed that the 'hacktoberfest-accepted' label hasn't been added to it yet.

Hacktoberfest is important to many contributors, including myself, and this label helps participants track their contributions. If it's not too much trouble, could you kindly add the 'hacktoberfest-accepted' label to this merged pull request? This would be greatly appreciated.

Thank you once again for your support, and I look forward to contributing more to this project in the future.

**Comment by LakshmanKishore** [comment]
Thank you so much for promptly adding the 'hacktoberfest-accepted' label to my pull request.
I look forward to more collaborations in the future.
Thank you!

**Pull request merged**
