### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ascillitoe**
Update `CONTRIBUTING.md` with a note on where to add class docstrings. 

Will do the same for `alibi` and delete the `contributing-update` branch upon merge.

### CODE REVIEW

**Comment by mauicv** [comment]
Shall we add a note for those of us who now us VS-code? :laughing: I'm using [this](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) extension

**Comment by mauicv** [comment]
Otherwise LGTM!

**Review by mauicv — APPROVED** [review]

**Comment by mauicv** [comment]
Actually another question: How do we document static classes or classes that don't implement an `__init__` method? The similarity method backends do [this](https://github.com/SeldonIO/alibi/blob/master/alibi/explainers/similarity/backends/pytorch/base.py) for example.

**Comment by ascillitoe** [comment]
> Shall we add a note for those of us who now us VS-code on how to set up auto docstrings? laughing I'm using [this](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) extension

Yuck... but yes good idea.



> Otherwise LGTM! Although why was the docs CI cancelled?

I don't know... perhaps because I authored the PR via the github UI and it doesn't touch the codebase?



> Actually another question: How do we document static classes or classes that don't implement an `__init__` method? The similarity method backends do [this](https://github.com/SeldonIO/alibi/blob/master/alibi/explainers/similarity/backends/pytorch/base.py) for example.

Good question. Maybe the convention should be "add docstring in __init__ if it exists, otherwise add to the class-level docstring"?

**Comment by ascillitoe** [comment]
@mauicv just updated following your comments.

**Pull request merged**
