### PR TITLE
New Docs PR

### PR DESCRIPTION
**Pull request by ramonpzg**
This PR contains the necessary changes to migrate to our new documentation platform, GitBook.

Previously, all notebooks were exported as markdown files during CI. Now, we will need to make changes to the notebooks and export them to a markdown file before committing the changes.

If you update 1 notebook you could use the [quarto CLI](https://quarto.org) and run the following command to update it from the terminal.

```sh
quarto convert overview.ipynb -o overview.md
```

If you update many notebooks and you want to convert them all at once, you can run the following command on the terminal.
```sh
for nb in *.ipynb; do 
  base_name="${nb%.ipynb}"
  quarto convert "$nb" -o "$base_name.md"
done
```
All files from the `doc/source` directory have been moved one lovely up, and all files related to `readthedocs` or `sphinx` have been deleted.

No changed have been made to the CI/CD pipeline. If we are running a command or several related to `readthedocs` and/or `sphinx`, these will need to be removed.

Lastly, there are no API references in this new documentation. These can be added later on or users can go to the source code to learn more about the implementation of a method.

### CODE REVIEW

**Comment by paulb-seldon** [comment]
A couple of initial notes:

- Any of the pages with {tab-item} (how read the docs does tab blocks) don't migrate well to gitbook (see the 'Getting Started' page)
- Latex or equations formatting doesn't translate between readthedocs and gitbook (see the Adversarial Auto-Encoder example)
- Does gitbook support syntax highlighting across languages? I can see for some of the python code blocks we don't really have it but would good for that to be consistent

**Comment by sakoush** [comment]
This PR should not overwrite `docs`, instead the new changes should go to `docs-gb` as with other workflows we have. 
This will by extension fix the merge conflicts above.

**Comment by Rajakavitha1** [comment]
> A couple of initial notes:
> 
> * Any of the pages with {tab-item} (how read the docs does tab blocks) don't migrate well to gitbook (see the 'Getting Started' page)
> * Latex or equations formatting doesn't translate between readthedocs and gitbook (see the Adversarial Auto-Encoder example)
> * Does gitbook support syntax highlighting across languages? I can see for some of the python code blocks we don't really have it but would good for that to be consistent

Hi @paulb-seldon  this is on my to do list post migration.

**Comment by Rajakavitha1** [comment]
> This PR should not overwrite `docs`, instead the new changes should go to `docs-gb` as with other workflows we have. This will by extension fix the merge conflicts above.

hi @sakoush  can you please help me with this move to `docs-gb` . I am afraid that I might mess up the folders. Could you please do this.

**Comment by sakoush** [comment]
superseded by https://github.com/SeldonIO/alibi-detect/pull/904

**Pull request closed without merging**
